options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'update-secrets'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ” Secret Manager æ›´æ–°é–‹å§‹..."

        if [ ! -f .env ]; then
          echo ".env ãƒ•ã‚¡ã‚¤ãƒ«ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ã€‚æ—¢å­˜ã®Secretã‚’ä½¿ç”¨ã—ã¾ã™ã€‚"
          exit 0
        fi

        echo '{' > env.json
        first=true
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
          if [[ "$line" == *"="* ]]; then
            key=$(echo "$line" | cut -d'=' -f1 | xargs)
            value=$(echo "$line" | cut -d'=' -f2- | xargs)
            value=$(echo "$value" | sed -e 's/^["'\'']//' -e 's/["'\'']$//')
            value=$(echo "$value" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> env.json
            fi
            printf '  "%s": "%s"' "$key" "$value" >> env.json
          fi
        done < .env
        echo '' >> env.json
        echo '}' >> env.json

        if ! gcloud secrets describe "cloudrun-sample-api-env" >/dev/null 2>&1; then
          gcloud secrets create "cloudrun-sample-api-env" --replication-policy="automatic"
        fi

        current_value=$(gcloud secrets versions access latest --secret="cloudrun-sample-api-env" || echo "")
        new_value=$(cat env.json)
        if [ "$current_value" != "$new_value" ]; then
          echo -n "$new_value" | gcloud secrets versions add "cloudrun-sample-api-env" --data-file=-
        fi

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloudrun-sample-api'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloudrun-sample-api'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy cloudrun-sample-api \
          --image "gcr.io/$PROJECT_ID/cloudrun-sample-api" \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --update-secrets "ENV_JSON=cloudrun-sample-api-env:latest"
